### ISSUE TITLE
Create a "FizzBuzz" Java Program

### ISSUE THREAD

**Issue by tangorishi** [tangorishi/learnJava#10]
Implement a Java program that prints numbers from 1 to 100, but for multiples of 3, print "Fizz," and for multiples of 5, print "Buzz." For numbers that are multiples of both 3 and 5, print "FizzBuzz."

**Comment by Ankit-Saha08** [comment]
Hii @tangorishi, I would definitely like to provide a solution for this problem. Will you please assign this task to me?? (hacktoberfest 2023)

**Comment by Ankit-Saha08** [comment]
**Please assign this issue to me, so that I can create a PR and contribute my solution!!**
@tangorishi

**Comment by Ankit-Saha08** [comment]
I request @tangorishi to kindly check my contribution to this issue in PR #15 and accept my contribution with "hacktoberfest-accepted" label.

**Comment by tangorishi** [comment]
Thanks for contributing @Ankit-Saha08

**Comment by tangorishi** [comment]
@Ankit-Saha08  you can add your github profile in the README.md file as you have successfully merged a PR then you can apply for another pull req

**Comment by Ankit-Saha08** [comment]
@tangorishi Ok  certainly I'll do that!!
