### ISSUE TITLE
Java Sorting Algorithm

### ISSUE THREAD

**Issue by tangorishi** [tangorishi/learnJava#11]
Implement a sorting algorithm in Java, such as bubble sort, selection sort, or merge sort, and provide test cases to verify its correctness.

**Comment by Tanishaclippy** [comment]
Can I work on this issue ?

**Comment by competitiveblood** [comment]
Can I work on this issue ?

**Comment by Janani-Balasooriya** [comment]
Can you assign me to this issue?
Thank you!

**Comment by tangorishi** [comment]
Sure thing @Janani-Balasooriya you can go ahead.
