### ISSUE TITLE
Palindrome Checker in Java

### ISSUE THREAD

**Issue by tangorishi** [tangorishi/learnJava#20]
Create a Java program that checks whether a given string is a palindrome (reads the same forwards and backward).

**Comment by Ankit-Saha08** [comment]
Hii @tangorishi, I would like  to contribute to this code as a part of your codebase.

**Comment by tangorishi** [comment]
@Ankit-Saha08  go ahead!!

**Comment by Ankit-Saha08** [comment]
Please check PR branch #46 for the solution to this issue. It's resolved!!
