### ISSUE TITLE
Number to Words Converter in Java

### ISSUE THREAD

**Issue by tangorishi** [tangorishi/learnJava#22]
Implement a Java program that converts a numeric input into its word representation (e.g., 123 as "one hundred twenty-three").

**Comment by Janani-Balasooriya** [comment]
Hi @tangorishi Can you assign me this issue?

**Comment by tangorishi** [comment]
@Janani-Balasooriya  go ahead

**Comment by Janani-Balasooriya** [comment]
> @Janani-Balasooriya go ahead

@tangorishi could you please tell me to which folder I should add the answer to this issue?
