### ISSUE TITLE
Random Password Generator in Java

### ISSUE THREAD

**Issue by tangorishi** [tangorishi/learnJava#23]
Create a Java class that generates strong and random passwords with specified criteria (length, complexity, etc.).

**Comment by tangorishi** [comment]
Go ahead @SumitMangrati make sure to follow the PR template in the README.md file before making the pull req

**Comment by SumitMangrati** [comment]
@tangorishi i have one doubt where do i save my code ? In the first contribution folder?

**Comment by tangorishi** [comment]
Hi you can save the code inside [this](https://github.com/tangorishi/learnJava/tree/main/16_FirstContribution) file.
