### ISSUE TITLE
Add Number Identification Problems

### ISSUE THREAD

**Issue by itsyourap** [tangorishi/learnJava#73]
Add Programs to identify these numbers:-
- Armstrong number
- Palindrome number
- Prime number
- Krishnamurthy number
- Happy number
- Automorphic number
- Kaprekar number
- Unique number
- Pronic number

**Comment by itsyourap** [comment]
@tangorishi Please assign this to me

**Comment by tangorishi** [comment]
@itsyourap go ahead
